### ISSUE TITLE
[BUG] It more of a visual issue.

### ISSUE THREAD

**Issue by SoulAttraction** [Nacandev/Ohmine-Dark-Theme-For-Joplin#14]
I greatly appreciate what you have done.  Its so much easier on my eye and I do stay focused more.

There are just two areas that my eyes are struggling with and have attempted to fix but unable.

I have attached a snappy to show you.

I appreciate your willingness to share your creation.

![Screen Shot 2022-03-01 at 2 47 08 PM](https://user-images.githubusercontent.com/33267354/156262676-56aa2e61-bb54-4532-bb3f-63623c92c6f2.png)
.

**Comment by Nacandev** [comment]
Hi there, the text color within your screenshot was not the default color of OhmineDT. Did you make any changes to it?

1, Please make sure you have changed the Joplin default theme to "dark" first. [more details](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin#appearance)

2, Please read and follow this guide: [Rich Markdown](#rich-markdown)

3, If still can't fix the problem, it would be related to your custom codes. Maybe you have to delete all the source codes within your `userchrome.css` and `userchrome.css`, and then read carefully the below:

- COMPLETE EXPERIENCE OF OHMINE DARK THEME
	- [1.Joplin Settings](#1-joplin-settings)
		- [Appearance](#appearance)
		- [Markdown](#markdown)
		- [Other Plugins](#other-plugins)
	- [2.Download & Install All Recommended Fonts](#2-download--install-all-recommended-fonts)
	- [3.Download & Install All Recommended Plugins](#3-download--install-all-recommended-plugins)
		- [Quick HTML Tags](#quick-html-tags)
		- [Rich Markdown](#rich-markdown)
		- [Markdown Table Colorize](#markdown-table-colorize)
		- [Spoiler](#spoiler)

Please follow the guide step by step.

3, In addition, I found that I didn't style the Notelist text color, so that's why you can't find out the CSS property. Thank you for letting me know, I'll add it in the next update.

**Comment by SoulAttraction** [comment]
No changes made -- but I found the issues.  Some how Joplin changed from dark theme back to white.  It may have been the upgrade.

Its back to normal now.

You did an awesome job on this!
