### ISSUE TITLE
[BUG] Emojis in titles are all blue in the rendering pannel

### ISSUE THREAD

**Issue by Klemet** [Nacandev/Ohmine-Dark-Theme-For-Joplin#3]
**1. Where did you meet the bug? (delete whichever is inapplicable)**

- Render Viewer

**2. Describe the bug**

Emojis in titles have lost their colours and details, being just blue blobs.

**3. To Reproduce**

1. Insert an emojis in a title.
2. Look at the rendering panel of the note.

**4. Expected behavior**

Emojis in titles should keep their colors.

**5. Screenshots**

![image](https://user-images.githubusercontent.com/41070328/139515219-fdc293dc-01ab-4653-800c-aae699f7f5ee.png)

becomes:

![image](https://user-images.githubusercontent.com/41070328/139515224-4c78216d-84c4-467b-86ce-8193d3b63b5b.png)

in the rendering panel.

Thank you for your theme : ) !

**Comment by Nacandev** [comment]
Hi there, due to the H1 heading is using the background clip effect, so you should use the emoji with a html span tag. [How to use the span tag](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin#span)

And if you want to use the html tag quickly, you can install the [Quick Html Tags plugin](https://github.com/Nacandev/Ohmine-Dark-Theme-For-Joplin#quick-html-tags-most-recommended-to-use-with-this-theme)

Or, if you want to remove the background clip effect from H1 heading, you should delete a few lines of code in `userchrome.css`.

As you see below is the CSS code about H1 heading:
```
#rendered-md > h1 {
  font-variant: small-caps;
  font-size: var(--h1-heading-size);
  color: var(--h1-text);
  background: var(--h1-clip-text);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  border-bottom: 1px solid var(--h1-border);
}
```
You should **delete** the this three lines:
```
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
```
But once you delete it, you will lost the gradient color on H1 heading.

**Comment by Klemet** [comment]
Thank you so much for providing those two workarounds ! I'll try them soon : ).

Meanwhile, I think that this issue can be marked as solved, since it seems to be a design choice rather than a bug.
